--!strict

return {
	calls = require("@kern/query/builtins/calls"),
	functions = require("@kern/query/builtins/functions"),
	locals = require("@kern/query/builtins/locals"),
	types = require("@kern/query/builtins/syntax_types"),
	tables = require("@kern/query/builtins/tables"),
	control_flow = require("@kern/query/builtins/control_flow"),
	strings = require("@kern/query/builtins/strings"),
	operators = require("@kern/query/builtins/operators"),
	modules = require("@kern/query/builtins/modules"),
	comments = require("@kern/query/builtins/comments"),
}
